version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - gocritic
    - revive
    - errorlint
    - gocyclo
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gomnd
          - dupl

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
